-- Created in 2018.06.03 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		create_archive_union_view.sql
--	Description:
-- 		创建数据库归档表联合视图与同义词
--  Relation:
--      对象关联
--	Notes:
--		基本注意事项
--	修改 - （年-月-日） - 描述
--

CREATE USER COMM     IDENTIFIED BY ZOE$2017AYEFY DEFAULT TABLESPACE COMM_TAB;
CREATE USER INPSICK  IDENTIFIED BY ZOE$2017AYEFY DEFAULT TABLESPACE INPSICK_TAB;
CREATE USER OUTPSICK IDENTIFIED BY ZOE$2017AYEFY DEFAULT TABLESPACE OUTPSICK_TAB;
CREATE USER PHYSIC   IDENTIFIED BY ZOE$2017AYEFY DEFAULT TABLESPACE PHYSIC_TAB;
GRANT CREATE VIEW TO COMM;
GRANT CREATE VIEW TO INPSICK;
GRANT CREATE VIEW TO OUTPSICK;
GRANT CREATE VIEW TO PHYSIC;


GRANT SELECT ON ZOEARCHIVE.APPLY_SHEET_A TO COMM;
GRANT SELECT ON ZOEARCHIVE.APPLY_SHEET_O TO COMM;
GRANT SELECT ON ZOEARCHIVE.APPLY_SHEET_DETAIL_A TO COMM;
GRANT SELECT ON ZOEARCHIVE.APPLY_SHEET_DETAIL_O TO COMM;
GRANT SELECT ON ZOEARCHIVE.PREPAYMENT_MONEY_A TO COMM;
GRANT SELECT ON ZOEARCHIVE.PREPAYMENT_MONEY_O TO COMM;
GRANT SELECT ON ZOEARCHIVE.RESIDENCE_SICK_PRICE_ITEM_A TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.RESIDENCE_SICK_PRICE_ITEM_O TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.PRESCRIBE_RECORD_A TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.PRESCRIBE_RECORD_O TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.SICK_SETTLE_MASTER_A TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.SICK_SETTLE_MASTER_O TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.SICK_SETTLE_DETAIL_A TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.SICK_SETTLE_DETAIL_O TO INPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_PRESCRIP_MASTER_A TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_PRESCRIP_MASTER_O TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_PRESCRIBE_DETAIL_A TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_PRESCRIBE_DETAIL_O TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_SICK_CURE_INFO_A TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_SICK_CURE_INFO_O TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_SICK_PRICE_ITEM_A TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.DISPENSARY_SICK_PRICE_ITEM_O TO OUTPSICK;
GRANT SELECT ON ZOEARCHIVE.LAY_PHYSIC_RECORDS_A TO PHYSIC;
GRANT SELECT ON ZOEARCHIVE.LAY_PHYSIC_RECORDS_O TO PHYSIC;

CREATE OR REPLACE VIEW COMM.APPLY_SHEET AS 
SELECT * FROM ZOEARCHIVE.APPLY_SHEET_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.APPLY_SHEET_O
;

CREATE OR REPLACE VIEW COMM.APPLY_SHEET_DETAIL AS 
SELECT * FROM ZOEARCHIVE.APPLY_SHEET_DETAIL_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.APPLY_SHEET_DETAIL_O
;

CREATE OR REPLACE VIEW COMM.PREPAYMENT_MONEY AS 
SELECT * FROM ZOEARCHIVE.PREPAYMENT_MONEY_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.PREPAYMENT_MONEY_O
;

CREATE OR REPLACE VIEW INPSICK.RESIDENCE_SICK_PRICE_ITEM AS 
SELECT * FROM ZOEARCHIVE.RESIDENCE_SICK_PRICE_ITEM_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.RESIDENCE_SICK_PRICE_ITEM_O
;

CREATE OR REPLACE VIEW INPSICK.PRESCRIBE_RECORD AS 
SELECT * FROM ZOEARCHIVE.PRESCRIBE_RECORD_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.PRESCRIBE_RECORD_O
;

CREATE OR REPLACE VIEW INPSICK.SICK_SETTLE_MASTER AS 
SELECT * FROM ZOEARCHIVE.SICK_SETTLE_MASTER_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.SICK_SETTLE_MASTER_O
;

CREATE OR REPLACE VIEW INPSICK.SICK_SETTLE_DETAIL AS 
SELECT * FROM ZOEARCHIVE.SICK_SETTLE_DETAIL_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.SICK_SETTLE_DETAIL_O
;

CREATE OR REPLACE VIEW OUTPSICK.DISPENSARY_PRESCRIP_MASTER AS 
SELECT * FROM ZOEARCHIVE.DISPENSARY_PRESCRIP_MASTER_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.DISPENSARY_PRESCRIP_MASTER_O
;

CREATE OR REPLACE VIEW OUTPSICK.DISPENSARY_PRESCRIBE_DETAIL AS 
SELECT * FROM ZOEARCHIVE.DISPENSARY_PRESCRIBE_DETAIL_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.DISPENSARY_PRESCRIBE_DETAIL_O
;

CREATE OR REPLACE VIEW OUTPSICK.DISPENSARY_SICK_PRICE_ITEM AS 
SELECT * FROM ZOEARCHIVE.DISPENSARY_SICK_PRICE_ITEM_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.DISPENSARY_SICK_PRICE_ITEM_O
;

CREATE OR REPLACE VIEW OUTPSICK.DISPENSARY_SICK_CURE_INFO AS 
SELECT * FROM ZOEARCHIVE.DISPENSARY_SICK_CURE_INFO_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.DISPENSARY_SICK_CURE_INFO_O
;

CREATE OR REPLACE VIEW PHYSIC.LAY_PHYSIC_RECORDS AS 
SELECT * FROM ZOEARCHIVE.LAY_PHYSIC_RECORDS_A
UNION ALL 
SELECT * FROM ZOEARCHIVE.LAY_PHYSIC_RECORDS_O
;


CREATE OR REPLACE PUBLIC SYNONYM APPLY_SHEET FOR COMM.APPLY_SHEET; 
CREATE OR REPLACE PUBLIC SYNONYM APPLY_SHEET_DETAIL FOR COMM.APPLY_SHEET_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM PREPAYMENT_MONEY FOR COMM.PREPAYMENT_MONEY;
CREATE OR REPLACE PUBLIC SYNONYM PRESCRIBE_RECORD FOR INPSICK.PRESCIRBE_RECORD;
CREATE OR REPLACE PUBLIC SYNONYM RESIDENCE_SICK_PRICE_ITEM FOR INPSICK.RESIDENCE_SICK_PRICE_ITEM;
CREATE OR REPLACE PUBLIC SYNONYM SICK_SETTLE_MASTER FOR INPSICK.SICK_SETTLE_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM SICK_SETTLE_DETAIL FOR INPSICK.SICK_SETTLE_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM DISPENSARY_PRESCRIP_MASTER FOR OUTPSICK.DISPENSARY_PRESCRIP_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM DISPENSARY_PRESCRIBE_DETAIL FOR OUTPSICK.DISPENSARY_PRESCRIBE_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM DISPENSARY_SICK_CURE_INFO FOR OUTPSICK.DISPENSARY_SICK_CURE_INFO;
CREATE OR REPLACE PUBLIC SYNONYM DISPENSARY_SICK_PRICE_ITEM FOR OUTPSICK.DISPENSARY_SICK_PRICE_ITEM;
CREATE OR REPLACE PUBLIC SYNONYM LAY_PHYSIC_RECORDS FOR PHYSIC.LAY_PHYSIC_RECORDS;


GRANT SELECT ON COMM.APPLY_SHEET TO ZOEARCHIVE;
GRANT SELECT ON COMM.APPLY_SHEET_DETAIL TO ZOEARCHIVE;
GRANT SELECT ON COMM.PREPAYMENT_MONEY TO ZOEARCHIVE;
GRANT SELECT ON INPSICK.PRESCRIBE_RECORD TO ZOEARCHIVE;
GRANT SELECT ON INPSICK.RESIDENCE_SICK_PRICE_ITEM TO ZOEARCHIVE;
GRANT SELECT ON INPSICK.SICK_SETTLE_MASTER TO ZOEARCHIVE;
GRANT SELECT ON INPSICK.SICK_SETTLE_DETAIL TO ZOEARCHIVE;
GRANT SELECT ON OUTPSICK.DISPENSARY_SICK_PRICE_ITEM TO ZOEARCHIVE;
GRANT SELECT ON OUTPSICK.DISPENSARY_PRESCRIP_MASTER TO ZOEARCHIVE;
GRANT SELECT ON OUTPSICK.DISPENSARY_PRESCRIBE_DETAIL TO ZOEARCHIVE;
GRANT SELECT ON OUTPSICK.DISPENSARY_SICK_CURE_INFO TO ZOEARCHIVE;
GRANT SELECT ON PHYSIC.LAY_PHYSIC_RECORDS TO ZOEARCHIVE;
