-- Created in 2018.06.03 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		create_archive_union_view.sql
--	Description:
-- 		创建数据库归档表联合视图与同义词
--  Relation:
--      对象关联
--	Notes:
--		基本注意事项
--	修改 - （年-月-日） - 描述
--

CREATE USER ZEMR     IDENTIFIED BY ZOE$2017AYEFY DEFAULT TABLESPACE ZEMR_TAB;
GRANT CREATE VIEW TO ZEMR;

GRANT SELECT ON ZOEARCHIVE.ZEMR_EMR_CONTENT_A                  TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_STD_PATIENT_INFO_DOMAIN_A      TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_MASTER_A                 TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_MASTER_ARCHIVE_A         TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_DETAIL_A                 TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_DETAIL_ARCHIVE_A         TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_EMR_PRINTLOG_A                 TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_TEMP_ARCHIVE_A           TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_TEMP_POINT_RECORD_A            TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_TEMPERATURE_FEVER_A            TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_TEMP_ENTIRE_RECORD_A           TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_PATIENT_DIAGNOSIS_A            TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_PATIENT_OPERATION_A            TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSESTAT_DETAIL_A             TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_BABY_MASTER_A            TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_NURSE_PATIENT_INFO_A           TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_TEMPERATURE_DAY_RECORD_A       TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_TEMPERATURE_WEEK_EMR _A        TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_BABYTP_RECORD_A                TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZQC_TIME_RULE_RECORD_A              TO ZEMR;
GRANT SELECT ON ZOEARCHIVE.ZEMR_REGISTER_EVENT_RECORD_A        TO ZEMR;

ALTER TABLE  ZEMR.ZEMR_EMR_CONTENT                  RENAME TO ZEMR_EMR_CONTENT_O;
ALTER TABLE  ZEMR.ZEMR_STD_PATIENT_INFO_DOMAIN      RENAME TO ZEMR_STD_PATIENT_INFO_DOMAIN_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_MASTER                 RENAME TO ZEMR_NURSE_MASTER_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_MASTER_ARCHIVE         RENAME TO ZEMR_NURSE_MASTER_ARCHIVE_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_DETAIL                 RENAME TO ZEMR_NURSE_DETAIL_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_DETAIL_ARCHIVE         RENAME TO ZEMR_NURSE_DETAIL_ARCHIVE_O;
ALTER TABLE  ZEMR.ZEMR_EMR_PRINTLOG                 RENAME TO ZEMR_EMR_PRINTLOG_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_TEMP_ARCHIVE           RENAME TO ZEMR_NURSE_TEMP_ARCHIVE_O;
ALTER TABLE  ZEMR.ZEMR_TEMPERATURE_POINT_RECORD     RENAME TO ZEMR_TEMP_POINT_RECORD_O;
ALTER TABLE  ZEMR.ZEMR_TEMPERATURE_FEVER            RENAME TO ZEMR_TEMPERATURE_FEVER_O;
ALTER TABLE  ZEMR.ZEMR_TEMPERATURE_ENTIRE_RECORD    RENAME TO ZEMR_TEMP_ENTIRE_RECORD_O;
ALTER TABLE  ZEMR.ZEMR_PATIENT_DIAGNOSIS            RENAME TO ZEMR_PATIENT_DIAGNOSIS_O;
ALTER TABLE  ZEMR.ZEMR_PATIENT_OPERATION            RENAME TO ZEMR_PATIENT_OPERATION_O;
ALTER TABLE  ZEMR.ZEMR_NURSESTAT_DETAIL             RENAME TO ZEMR_NURSESTAT_DETAIL_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_BABY_MASTER            RENAME TO ZEMR_NURSE_BABY_MASTER_O;
ALTER TABLE  ZEMR.ZEMR_NURSE_PATIENT_INFO           RENAME TO ZEMR_NURSE_PATIENT_INFO_O;
ALTER TABLE  ZEMR.ZEMR_TEMPERATURE_DAY_RECORD       RENAME TO ZEMR_TEMPERATURE_DAY_RECORD_O;
ALTER TABLE  ZEMR.ZEMR_TEMPERATURE_WEEK_EMR         RENAME TO ZEMR_TEMPERATURE_WEEK_EMR_O;
ALTER TABLE  ZEMR.ZEMR_BABYTP_RECORD                RENAME TO ZEMR_BABYTP_RECORD_O;
ALTER TABLE  ZEMR.ZQC_TIME_RULE_RECORD              RENAME TO ZQC_TIME_RULE_RECORD_O;
ALTER TABLE  ZEMR.ZEMR_REGISTER_EVENT_RECORD        RENAME TO ZEMR_REGISTER_EVENT_RECORD_O;


         
CREATE OR REPLACE VIEW ZEMR.ZEMR_EMR_CONTENT                AS SELECT * FROM ZOEARCHIVE.ZEMR_EMR_CONTENT_A                UNION ALL SELECT * FROM ZEMR_EMR_CONTENT_O                WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_STD_PATIENT_INFO_DOMAIN    AS SELECT * FROM ZOEARCHIVE.ZEMR_STD_PATIENT_INFO_DOMAIN_A    UNION ALL SELECT * FROM ZEMR_STD_PATIENT_INFO_DOMAIN_O    WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_MASTER               AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_MASTER_A               UNION ALL SELECT * FROM ZEMR_NURSE_MASTER_O               WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_MASTER_ARCHIVE       AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_MASTER_ARCHIVE_A       UNION ALL SELECT * FROM ZEMR_NURSE_MASTER_ARCHIVE_O       WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_DETAIL               AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_DETAIL_A               UNION ALL SELECT * FROM ZEMR_NURSE_DETAIL_O               WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_DETAIL_ARCHIVE       AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_DETAIL_ARCHIVE_A       UNION ALL SELECT * FROM ZEMR_NURSE_DETAIL_ARCHIVE_O       WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_EMR_PRINTLOG               AS SELECT * FROM ZOEARCHIVE.ZEMR_EMR_PRINTLOG_A               UNION ALL SELECT * FROM ZEMR_EMR_PRINTLOGO                WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_TEMP_ARCHIVE         AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_TEMP_ARCHIVE_A         UNION ALL SELECT * FROM ZEMR_NURSE_TEMP_ARCHIVE_O         WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_TEMPERATURE_POINT_RECORD   AS SELECT * FROM ZOEARCHIVE.ZEMR_TEMP_POINT_RECORD_A          UNION ALL SELECT * FROM ZEMR_TEMP_POINT_RECORD_O   WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_TEMPERATURE_FEVER          AS SELECT * FROM ZOEARCHIVE.ZEMR_TEMPERATURE_FEVER_A          UNION ALL SELECT * FROM ZEMR_TEMPERATURE_FEVER_O          WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_TEMPERATURE_ENTIRE_RECORD  AS SELECT * FROM ZOEARCHIVE.ZEMR_TEMP_ENTIRE_RECORD_A         UNION ALL SELECT * FROM ZEMR_TEMP_ENTIRE_RECORD_O  WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_PATIENT_DIAGNOSIS          AS SELECT * FROM ZOEARCHIVE.ZEMR_PATIENT_DIAGNOSIS_A          UNION ALL SELECT * FROM ZEMR_PATIENT_DIAGNOSIS_O          WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_PATIENT_OPERATION          AS SELECT * FROM ZOEARCHIVE.ZEMR_PATIENT_OPERATION_A          UNION ALL SELECT * FROM ZEMR_PATIENT_OPERATION_O          WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSESTAT_DETAIL           AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSESTAT_DETAIL_A           UNION ALL SELECT * FROM ZEMR_NURSESTAT_DETAIL_O           WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_BABY_MASTER          AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_BABY_MASTER_A          UNION ALL SELECT * FROM ZEMR_NURSE_BABY_MASTER_O          WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_NURSE_PATIENT_INFO         AS SELECT * FROM ZOEARCHIVE.ZEMR_NURSE_PATIENT_INFO_A         UNION ALL SELECT * FROM ZEMR_NURSE_PATIENT_INFO_O         WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_TEMPERATURE_DAY_RECORD     AS SELECT * FROM ZOEARCHIVE.ZEMR_TEMPERATURE_DAY_RECORD_A     UNION ALL SELECT * FROM ZEMR_TEMPERATURE_DAY_RECORD_O     WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_TEMPERATURE_WEEK_EMR       AS SELECT * FROM ZOEARCHIVE.ZEMR_TEMPERATURE_WEEK_EMR_A       UNION ALL SELECT * FROM ZEMR_TEMPERATURE_WEEK_EMR_O       WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZEMR_BABYTP_RECORD              AS SELECT * FROM ZOEARCHIVE.ZEMR_BABYTP_RECORD_A              UNION ALL SELECT * FROM ZEMR_BABYTP_RECORD_O              WITH READ ONLY;
CREATE OR REPLACE VIEW ZEMR.ZQC_TIME_RULE_RECORD            AS SELECT * FROM ZOEARCHIVE.ZQC_TIME_RULE_RECORD_A            UNION ALL SELECT * FROM ZQC_TIME_RULE_RECORD_O            WITH READ ONLY; 
CREATE OR REPLACE VIEW ZEMR.ZEMR_REGISTER_EVENT_RECORD      AS SELECT * FROM ZOEARCHIVE.ZEMR_REGISTER_EVENT_RECORD_A      UNION ALL SELECT * FROM ZEMR_REGISTER_EVENT_RECORD_O      WITH READ ONLY;  




GRANT SELECT ON ZEMR.ZEMR_EMR_CONTENT_O                  TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_STD_PATIENT_INFO_DOMAIN_O      TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_MASTER_O                 TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_MASTER_ARCHIVE_O         TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_DETAIL_O                 TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_DETAIL_ARCHIVE_O         TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_EMR_PRINTLOG_O                 TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_TEMP_ARCHIVE_O           TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_TEMP_POINT_RECORD_O            TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_TEMPERATURE_FEVER_O            TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_TEMP_ENTIRE_RECORD_O           TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_PATIENT_DIAGNOSIS_O            TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_PATIENT_OPERATION_O            TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSESTAT_DETAIL_O             TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_BABY_MASTER_O            TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_NURSE_PATIENT_INFO_O           TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_TEMPERATURE_DAY_RECORD_O       TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_TEMPERATURE_WEEK_EMR_O         TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_BABYTP_RECORD_O                TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZQC_TIME_RULE_RECORD_O              TO ZOEARCHIVE;
GRANT SELECT ON ZEMR.ZEMR_REGISTER_EVENT_RECORD_O        TO ZOEARCHIVE;