CREATE TABLE ZOEARCHIVE.SICK_SETTLE_MASTER 
	(SICK_ID VARCHAR2(64), VISIT_NUMBER VARCHAR2(64), RESIDENCE_NO VARCHAR2(64),
	SETTLE_DATE DATE,SETTLE_MODE VARCHAR2(64),OUT_WARD_SETTLE_TYPE VARCHAR2(64),
	SETTLE_NO VARCHAR2(64),settle_type VARCHAR2(64),back_receipt_no VARCHAR2(64));
	
CREATE TABLE ZOEARCHIVE.SICK_VISIT_INFO
	(SICK_ID VARCHAR2(64), VISIT_NUMBER VARCHAR2(64), RESIDENCE_NO VARCHAR2(64),
	STATE VARCHAR2(64));
	
CREATE TABLE ZOEARCHIVE.prepayment_money
	(SICK_ID VARCHAR2(64), VISIT_NUMBER VARCHAR2(64), settle_receipt_no VARCHAR2(64),
	receipt_no VARCHAR2(64), operation_type VARCHAR2(64));