OPTIONS (skip=1,rows=32)
LOAD DATA
INFILE 'c:\zoedir\data\table_name.csv'
APPEND
INTO TABLE table_owner.table_name
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(COLUMN_NAME01,COLUMN_NAME02,COLUMN_NAME03)