-- Created in 2017.10.10 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		zoesql_create_user.sql
--	Description:
-- 		创建智业HIS5索引表空间
--  Relation:
--      
--	Notes:
--		
--	修改 - （年-月-日） - 描述

-- 2018年12月18日 上午 增加
CREATE INDEX CHA_INP_CHARGE_DETAIL_EVENT              ON ZOECHARGE.CHA_INP_CHARGE_DETAIL            (EVENT_NO)                       TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_INP_CHARGE_DETAIL_PATIENT            ON ZOECHARGE.CHA_INP_CHARGE_DETAIL            (PATIENT_ID)                     TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_OUTP_CHARGE_DETAIL_PATIENT           ON ZOECHARGE.CHA_OUTP_CHARGE_DETAIL           (PATIENT_ID)                     TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_OUTP_CHARGE_DETAIL_EVENT             ON ZOECHARGE.CHA_OUTP_CHARGE_DETAIL           (EVENT_NO)                       TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_OUTP_CONSUME_MASTER_EVENT            ON ZOECHARGE.CHA_OUTP_CONSUME_MASTER          (EVENT_NO)                       TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_OUTP_CONSUME_MASTER_PATIENT          ON ZOECHARGE.CHA_OUTP_CONSUME_MASTER          (PATIENT_ID)                     TABLESPACE ZOECHARGE_IND;
CREATE INDEX CHA_OUTP_PREPAY_RECORD_PATIENT           ON ZOECHARGE.CHA_OUTP_PREPAY_RECORD           (PATIENT_ID)                     TABLESPACE ZOECHARGE_IND;
CREATE INDEX COM_CARD_BASIC_INFO_PATIENT              ON ZOECOMM.COM_CARD_BASIC_INFO                (PATIENT_ID)                     TABLESPACE ZOECOMM_IND;
CREATE INDEX COM_CARD_DEPOSIT_RECORD_PATIENT          ON ZOECOMM.COM_CARD_DEPOSIT_RECORD            (PATIENT_ID)                     TABLESPACE ZOECOMM_IND;
CREATE INDEX COM_CARD_MAINTAIN_RECORD_PATIENT         ON ZOECOMM.COM_CARD_MAINTAIN_RECORD           (PATIENT_ID)                     TABLESPACE ZOECOMM_IND;
CREATE INDEX COM_CARD_MAINTAIN_RECORD_CARD            ON ZOECOMM.COM_CARD_MAINTAIN_RECORD           (CARD_ID)                        TABLESPACE ZOECOMM_IND;
CREATE INDEX EMR_PATIENT_DE_VALUE_PATIENT             ON ZOEEMR.EMR_PATIENT_DE_VALUE                (PATIENT_ID)                     TABLESPACE ZOEEMR_IND;
CREATE INDEX INS_INP_TRANSFER_DETAIL_PATIENT          ON ZOEINSUR.INS_INP_TRANSFER_DETAIL           (PATIENT_ID)                     TABLESPACE ZOEINSUR_IND;
CREATE INDEX MSG_MESSAGE_RECORD_PATIENT               ON ZOEMSG.MSG_MESSAGE_RECORD                  (PATIENT_ID)                     TABLESPACE ZOEMSG_IND;
CREATE INDEX MSG_MESSAGE_RECORD_EVENT                 ON ZOEMSG.MSG_MESSAGE_RECORD                  (EVENT_NO)                       TABLESPACE ZOEMSG_IND;
CREATE INDEX PAT_BASIC_INFO_CARD                      ON ZOEPATIENT.PAT_BASIC_INFO                  (CARD_ID)                        TABLESPACE ZOEPATIENT_IND;
CREATE INDEX PRES_APPLY_RECORDS_POOL_EVENT            ON ZOEPRES.PRES_APPLY_RECORDS_POOL            (EVENT_NO)                       TABLESPACE ZOEPRES_IND;
CREATE INDEX PRES_APPLY_RECORDS_POOL_PATIENT          ON ZOEPRES.PRES_APPLY_RECORDS_POOL            (PATIENT_ID)                     TABLESPACE ZOEPRES_IND;