SELECT 'CREATE INDEX '||A.OWNER||'.'||INDEX_NAME||' ON '||A.TABLE_OWNER||'.'||A.TABLE_NAME||'('||
       (SELECT LISTAGG(COLUMN_NAME,',') WITHIN GROUP(ORDER BY B.COLUMN_POSITION)
          FROM DBA_IND_COLUMNS B
         WHERE A.OWNER = B.INDEX_OWNER
           AND A.INDEX_NAME = B.INDEX_NAME
           AND A.TABLE_OWNER = B.TABLE_OWNER
           AND A.TABLE_NAME = B.TABLE_NAME)||') ONLINE;' AS MDB_INDEX,
       'CREATE INDEX '||DECODE(A.OWNER,'ZOEEMR','ZOEODS_EMR','ZOEODS_HIS')||'.'||INDEX_NAME||' ON '||DECODE(A.TABLE_OWNER,'ZOEEMR','ZOEODS_EMR','ZOEODS_HIS')||'.'||A.TABLE_NAME||'('||
       (SELECT LISTAGG(COLUMN_NAME,',') WITHIN GROUP(ORDER BY B.COLUMN_POSITION)
          FROM DBA_IND_COLUMNS B
         WHERE A.OWNER = B.INDEX_OWNER
           AND A.INDEX_NAME = B.INDEX_NAME
           AND A.TABLE_OWNER = B.TABLE_OWNER
           AND A.TABLE_NAME = B.TABLE_NAME)||') ONLINE;' AS HDC_INDEX
  FROM DBA_INDEXES A
 WHERE OWNER LIKE 'ZOE%'
   AND OWNER <> 'ZOETMP'
   AND OWNER <> 'ZOEDBA'
   AND INDEX_TYPE = 'NORMAL'
   AND UNIQUENESS = 'NONUNIQUE'
 ORDER BY A.TABLE_OWNER,
          A.TABLE_NAME;
