CREATE OR REPLACE FUNCTION zoetmp.get_data_for_insert_new(iv_owner VARCHAR2, 
                                                          iv_table_name VARCHAR2,
														  iv_new_owner VARCHAR2,
														  iv_new_table_name VARCHAR2,
														  id_last_date      DATE)
RETURN NUMBER
AS
--用于以INSERT语句方式从ORACLE数据库导出指定表的数据
	lv_columns             VARCHAR2(32767) := '';
	lv_condition           VARCHAR2(400) := ' 1=1 ';
	lv_sql                 VARCHAR2(32767) := '';
	lv_column_vaulue       VARCHAR2(32767) := '';
	TYPE C_TYPE IS REF CURSOR;
	ltc_get_column_vaulue C_TYPE;
BEGIN
    IF id_last_date IS NULL THEN
       lv_condition := ' 1=1 ';
    ELSE
	   --这两个表全量同步
       if upper(iv_table_name) = 'COM_I18N_DICT_CLASS_DIST' or upper(iv_table_name) = 'COM_I18N_DICT_CLASS' then
          lv_condition := ' 1=1 ';
       else
          lv_condition := ' 1=1 and MODIFIED_TIME >= to_date('''||to_char(id_last_date,'yyyy-mm-dd')||''',''yyyy-mm-dd'')';
       end if;
    END IF;
    
	FOR lc_record IN (SELECT COLUMN_NAME 
	                    FROM DBA_TAB_COLUMNS 
					   WHERE OWNER = iv_owner AND TABLE_NAME = iv_table_name
					   ORDER BY COLUMN_ID)
	LOOP
		lv_columns :=  lv_columns||','||lc_record.COLUMN_NAME;
	END LOOP;
	lv_columns := SUBSTR(lv_columns,2);
	DBMS_OUTPUT.ENABLE (BUFFER_SIZE=>NULL) ;
	FOR lc_record IN (SELECT COLUMN_NAME,
	                         DATA_TYPE 
	                    FROM DBA_TAB_COLUMNS 
					   WHERE OWNER = iv_owner 
					     AND TABLE_NAME = iv_table_name
					   ORDER BY COLUMN_ID)
	LOOP
		IF  lc_record.DATA_TYPE = 'VARCHAR2' THEN        
			lv_sql :=  lv_sql||'||'',''||'||'DECODE('||lc_record.COLUMN_NAME||',NULL,''NULL'',''''''''||' ||lc_record.COLUMN_NAME||'||'''''''')';
		ELSIF   lc_record.DATA_TYPE = 'DATE' THEN        
			lv_sql := lv_sql||'||'',''||'||'DECODE('||lc_record.COLUMN_NAME||  ',NULL,''NULL'',''TO_DATE(''''''||TO_CHAR('  ||lc_record.COLUMN_NAME|| ',''YYYY-MM-DD HH24:MI:SS'')||'''''', ''''YYYY-MM-DD HH24:MI:SS'''')'')';
		ELSE  
			lv_sql :=  lv_sql||'||'',''||'||'DECODE('||lc_record.COLUMN_NAME||',NULL,''NULL'','||lc_record.COLUMN_NAME||')';
		END IF;   
	 END LOOP;   
	 lv_sql := SUBSTR(lv_sql,8);
	 IF lv_sql IS NULL THEN 
		DBMS_OUTPUT.PUT_LINE('lv_sql NULL');
		RETURN -1;
	 END IF;
        lv_sql := 'SELECT '|| lv_sql ||' FROM '||iv_owner|| '.' || iv_table_name || ' WHERE ' || lv_condition;
	  OPEN ltc_get_column_vaulue FOR lv_sql;
	  FETCH ltc_get_column_vaulue INTO lv_column_vaulue;
	   LOOP
			EXIT WHEN ltc_get_column_vaulue%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE('INSERT INTO '||iv_new_owner|| '.' || iv_new_table_name || '('|| lv_columns ||')  VALUES ('|| lv_column_vaulue ||');');
			FETCH ltc_get_column_vaulue INTO lv_column_vaulue;
		END LOOP;
--	  DBMS_OUTPUT.PUT_LINE('INSERT INTO '||iv_owner|| '.' || iv_table_name || '('|| lv_columns ||')  VALUES ('|| lv_column_vaulue ||');');
      RETURN 1;
END;
/
set feedback off
set serveroutput on 
spool c:\zoedir\scripts\tabledata_i18n.sql
declare
v_return varchar2(64);
begin
    DBMS_OUTPUT.PUT_LINE('spool c:\zoedir\log\tabledata_i18n.log');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_CLASS PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_CLASS_DIST PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_INFO PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_LANG_INFO PURGE;');

    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_CLASS_TMP PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_INFO_TMP PURGE;');
    DBMS_OUTPUT.PUT_LINE('DROP TABLE ZOETMP.COM_I18N_DICT_LANG_INFO_TMP PURGE;');

    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_CLASS  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_CLASS;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_CLASS_DIST  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_CLASS_DIST;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_INFO  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_INFO;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_LANG_INFO  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_LANG_INFO;');

    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_CLASS_TMP  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_CLASS WHERE 1=2;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_CLASS_DIST WHERE 1=2;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_INFO_TMP  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_INFO WHERE 1=2;');
    DBMS_OUTPUT.PUT_LINE('CREATE TABLE ZOETMP.COM_I18N_DICT_LANG_INFO_TMP  AS SELECT * FROM ZOECOMM.COM_I18N_DICT_LANG_INFO WHERE 1=2;');
    
    v_return := zoetmp.get_data_for_insert_new('ZOECOMM','COM_I18N_DICT_CLASS','ZOETMP','COM_I18N_DICT_CLASS_TMP',NULL);
    v_return := zoetmp.get_data_for_insert_new('ZOECOMM','COM_I18N_DICT_CLASS_DIST','ZOETMP','COM_I18N_DICT_CLASS_DIST_TMP',NULL);
    v_return := zoetmp.get_data_for_insert_new('ZOECOMM','COM_I18N_DICT_INFO','ZOETMP','COM_I18N_DICT_INFO_TMP',NULL);
    v_return := zoetmp.get_data_for_insert_new('ZOECOMM','COM_I18N_DICT_LANG_INFO','ZOETMP','COM_I18N_DICT_LANG_INFO_TMP',NULL);
	
	--先做更新再做插入
	DBMS_OUTPUT.PUT_LINE('UPDATE ZOECOMM.COM_I18N_DICT_CLASS');
	DBMS_OUTPUT.PUT_LINE('   SET (I18N_DICT_CLASS_NAME,PARENT_I18N_CLASS_CODE,SORT_NO,MEMO,VALID_FLAG,SPELL_CODE,WBZX_CODE,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) ');
    DBMS_OUTPUT.PUT_LINE('     = (SELECT I18N_DICT_CLASS_NAME,PARENT_I18N_CLASS_CODE,SORT_NO,MEMO,VALID_FLAG,SPELL_CODE,WBZX_CODE,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME ');
    DBMS_OUTPUT.PUT_LINE('          FROM ZOETMP.COM_I18N_DICT_CLASS_TMP ');
    DBMS_OUTPUT.PUT_LINE('         WHERE ZOETMP.COM_I18N_DICT_CLASS_TMP.I18N_DICT_CLASS_CODE = ZOECOMM.COM_I18N_DICT_CLASS.I18N_DICT_CLASS_CODE)');
    DBMS_OUTPUT.PUT_LINE(' WHERE EXISTS (SELECT 1 ');
    DBMS_OUTPUT.PUT_LINE('         FROM ZOETMP.COM_I18N_DICT_CLASS_TMP ');
    DBMS_OUTPUT.PUT_LINE('        WHERE ZOETMP.COM_I18N_DICT_CLASS_TMP.I18N_DICT_CLASS_CODE = ZOECOMM.COM_I18N_DICT_CLASS.I18N_DICT_CLASS_CODE);');
	
    DBMS_OUTPUT.PUT_LINE('UPDATE ZOECOMM.COM_I18N_DICT_CLASS_DIST ');
    DBMS_OUTPUT.PUT_LINE('   SET (OPERATOR_CODE,OPERATOR_TIME) = (SELECT OPERATOR_CODE,OPERATOR_TIME ');
    DBMS_OUTPUT.PUT_LINE('                                          FROM ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP ');
    DBMS_OUTPUT.PUT_LINE('                                         WHERE ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_DICT_CLASS_CODE = ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_DICT_CLASS_CODE');
    DBMS_OUTPUT.PUT_LINE('                                           AND ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_ITEM_CODE)');
    DBMS_OUTPUT.PUT_LINE(' WHERE EXISTS (SELECT 1 ');
    DBMS_OUTPUT.PUT_LINE('                 FROM ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP ');
    DBMS_OUTPUT.PUT_LINE('                WHERE ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_DICT_CLASS_CODE = ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_DICT_CLASS_CODE');
	DBMS_OUTPUT.PUT_LINE('                  AND ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_ITEM_CODE);');
	
	DBMS_OUTPUT.PUT_LINE('UPDATE ZOECOMM.COM_I18N_DICT_INFO ');
	DBMS_OUTPUT.PUT_LINE('   SET (I18N_ITEM_EXPLAIN,SORT_NO,MEMO,VALID_FLAG,SPELL_CODE,WBZX_CODE,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME,NOT_SYNC)'); 
	DBMS_OUTPUT.PUT_LINE('       = (SELECT I18N_ITEM_EXPLAIN,SORT_NO,MEMO,VALID_FLAG,SPELL_CODE,WBZX_CODE,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME,NOT_SYNC');
	DBMS_OUTPUT.PUT_LINE('            FROM ZOETMP.COM_I18N_DICT_INFO_TMP ');
	DBMS_OUTPUT.PUT_LINE('           WHERE ZOETMP.COM_I18N_DICT_INFO_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_INFO.I18N_ITEM_CODE)');
	DBMS_OUTPUT.PUT_LINE(' WHERE EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                 FROM ZOETMP.COM_I18N_DICT_INFO_TMP ');
	DBMS_OUTPUT.PUT_LINE('                WHERE ZOETMP.COM_I18N_DICT_INFO_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_INFO.I18N_ITEM_CODE)');
	DBMS_OUTPUT.PUT_LINE('   AND NVL(NOT_SYNC,''0'') = ''0'';');
	
	DBMS_OUTPUT.PUT_LINE('UPDATE ZOECOMM.COM_I18N_DICT_LANG_INFO ');
	DBMS_OUTPUT.PUT_LINE('   SET (LANGUAGE_TRANSLATION,SORT_NO,MEMO,MODIFIER_CODE,MODIFIED_TIME,NOT_SYNC) ');
	DBMS_OUTPUT.PUT_LINE('       = (SELECT LANGUAGE_TRANSLATION,SORT_NO,MEMO,MODIFIER_CODE,MODIFIED_TIME,NOT_SYNC ');
	DBMS_OUTPUT.PUT_LINE('            FROM ZOETMP.COM_I18N_DICT_LANG_INFO_TMP ');
	DBMS_OUTPUT.PUT_LINE('           WHERE ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_ITEM_CODE');
	DBMS_OUTPUT.PUT_LINE('             AND ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_CLASS = ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_CLASS)');
	DBMS_OUTPUT.PUT_LINE(' WHERE EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                 FROM ZOETMP.COM_I18N_DICT_LANG_INFO_TMP ');
	DBMS_OUTPUT.PUT_LINE('                WHERE ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_ITEM_CODE = ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_ITEM_CODE');
	DBMS_OUTPUT.PUT_LINE('                  AND ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_CLASS = ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_CLASS)');
	DBMS_OUTPUT.PUT_LINE('   AND NVL(NOT_SYNC,''0'') = ''0'';');
	
	--插入没有的数据
	DBMS_OUTPUT.PUT_LINE('INSERT INTO ZOECOMM.COM_I18N_DICT_CLASS');
	DBMS_OUTPUT.PUT_LINE('SELECT * FROM ZOETMP.COM_I18N_DICT_CLASS_TMP');
	DBMS_OUTPUT.PUT_LINE(' WHERE NOT EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                     FROM ZOECOMM.COM_I18N_DICT_CLASS');
	DBMS_OUTPUT.PUT_LINE('                    WHERE ZOECOMM.COM_I18N_DICT_CLASS.I18N_DICT_CLASS_CODE = ZOETMP.COM_I18N_DICT_CLASS_TMP.I18N_DICT_CLASS_CODE);');

	DBMS_OUTPUT.PUT_LINE('INSERT INTO ZOECOMM.COM_I18N_DICT_CLASS_DIST');
	DBMS_OUTPUT.PUT_LINE('SELECT * FROM ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP');
	DBMS_OUTPUT.PUT_LINE(' WHERE NOT EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                     FROM ZOECOMM.COM_I18N_DICT_CLASS_DIST');
	DBMS_OUTPUT.PUT_LINE('                    WHERE ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_DICT_CLASS_CODE = ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_DICT_CLASS_CODE');
	DBMS_OUTPUT.PUT_LINE('                      AND ZOECOMM.COM_I18N_DICT_CLASS_DIST.I18N_ITEM_CODE = ZOETMP.COM_I18N_DICT_CLASS_DIST_TMP.I18N_ITEM_CODE);');

	DBMS_OUTPUT.PUT_LINE('INSERT INTO ZOECOMM.COM_I18N_DICT_INFO');
	DBMS_OUTPUT.PUT_LINE('SELECT * FROM ZOETMP.COM_I18N_DICT_INFO_TMP');
	DBMS_OUTPUT.PUT_LINE(' WHERE NOT EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                     FROM ZOECOMM.COM_I18N_DICT_INFO');
	DBMS_OUTPUT.PUT_LINE('                    WHERE ZOECOMM.COM_I18N_DICT_INFO.I18N_ITEM_CODE = ZOETMP.COM_I18N_DICT_INFO_TMP.I18N_ITEM_CODE);');

	DBMS_OUTPUT.PUT_LINE('INSERT INTO ZOECOMM.COM_I18N_DICT_LANG_INFO');
	DBMS_OUTPUT.PUT_LINE('SELECT * FROM ZOETMP.COM_I18N_DICT_LANG_INFO_TMP');
	DBMS_OUTPUT.PUT_LINE(' WHERE NOT EXISTS (SELECT 1 ');
	DBMS_OUTPUT.PUT_LINE('                     FROM ZOECOMM.COM_I18N_DICT_LANG_INFO');
	DBMS_OUTPUT.PUT_LINE('                    WHERE ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_ITEM_CODE = ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_ITEM_CODE');
	DBMS_OUTPUT.PUT_LINE('                      AND ZOECOMM.COM_I18N_DICT_LANG_INFO.I18N_CLASS = ZOETMP.COM_I18N_DICT_LANG_INFO_TMP.I18N_CLASS);');
	
    DBMS_OUTPUT.PUT_LINE('COMMIT;');
    DBMS_OUTPUT.PUT_LINE('SPOOL OFF');
end; 
/
spool off
set feedback on
DROP FUNCTION zoetmp.get_data_for_insert_new;



