-- Created in 2018.06.03 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		release_step.sql
--	Description:
-- 		HIS5.0发布步骤
--  Relation:
--      对象关联
--	Notes:
--		基本注意事项
--	修改 - （年-月-日） - 描述
--



--数据处理
	--同步消息中心数据
		TRUNCATE TABLE ZOETMP.MSG_EVENT_MESSAGE_CONFIG    ;
		TRUNCATE TABLE ZOETMP.MSG_SYSTEM_VAR_DICT         ;
		TRUNCATE TABLE ZOETMP.MSG_EVENT_RECEIVE_INTERFACE ;
		TRUNCATE TABLE ZOETMP.MSG_EVENT_DICT              ;
		INSERT INTO    ZOETMP.MSG_EVENT_MESSAGE_CONFIG      SELECT * FROM ZOEMSG.MSG_EVENT_MESSAGE_CONFIG   ;
		INSERT INTO    ZOETMP.MSG_SYSTEM_VAR_DICT           SELECT * FROM ZOEMSG.MSG_SYSTEM_VAR_DICT        ;
		INSERT INTO    ZOETMP.MSG_EVENT_RECEIVE_INTERFACE   SELECT * FROM ZOEMSG.MSG_EVENT_RECEIVE_INTERFACE;
		INSERT INTO    ZOETMP.MSG_EVENT_DICT                SELECT * FROM ZOEMSG.MSG_EVENT_DICT             ;
		TRUNCATE TABLE ZOEMSG.MSG_EVENT_MESSAGE_CONFIG    ;  
		TRUNCATE TABLE ZOEMSG.MSG_SYSTEM_VAR_DICT         ;
		TRUNCATE TABLE ZOEMSG.MSG_EVENT_RECEIVE_INTERFACE ;
		TRUNCATE TABLE ZOEMSG.MSG_EVENT_DICT              ;
		INSERT INTO    ZOEMSG.MSG_EVENT_MESSAGE_CONFIG      SELECT * FROM ZOEMSG.MSG_EVENT_MESSAGE_CONFIG@zoecdb41zoemdb    ;
		INSERT INTO    ZOEMSG.MSG_SYSTEM_VAR_DICT           SELECT * FROM ZOEMSG.MSG_SYSTEM_VAR_DICT@zoecdb41zoemdb         ;
		INSERT INTO    ZOEMSG.MSG_EVENT_RECEIVE_INTERFACE   SELECT * FROM ZOEMSG.MSG_EVENT_RECEIVE_INTERFACE@zoecdb41zoemdb ;
		INSERT INTO    ZOEMSG.MSG_EVENT_DICT                SELECT * FROM ZOEMSG.MSG_EVENT_DICT@zoecdb41zoemdb              ;
		
	--同步规则中心数据
		TRUNCATE TABLE ZOETMP.RUL_RULE                  ;
		TRUNCATE TABLE ZOETMP.RUL_MODEL_PROPERTY_DS_CFG ;
		TRUNCATE TABLE ZOETMP.RUL_RULE_CONTENT          ;
		TRUNCATE TABLE ZOETMP.RUL_RULE_LABEL            ;
		TRUNCATE TABLE ZOETMP.RUL_RULE_LABEL_MAP        ;
		TRUNCATE TABLE ZOETMP.RUL_SYSTEM_VARIABLE       ;
		INSERT INTO    ZOETMP.RUL_RULE                    SELECT * FROM ZOERULE.RUL_RULE                  ;
		INSERT INTO    ZOETMP.RUL_MODEL_PROPERTY_DS_CFG   SELECT * FROM ZOERULE.RUL_MODEL_PROPERTY_DS_CFG ;
		INSERT INTO    ZOETMP.RUL_RULE_CONTENT            SELECT * FROM ZOERULE.RUL_RULE_CONTENT          ;
		INSERT INTO    ZOETMP.RUL_RULE_LABEL              SELECT * FROM ZOERULE.RUL_RULE_LABEL            ;
		INSERT INTO    ZOETMP.RUL_RULE_LABEL_MAP          SELECT * FROM ZOERULE.RUL_RULE_LABEL_MAP        ;
		INSERT INTO    ZOETMP.RUL_SYSTEM_VARIABLE         SELECT * FROM ZOERULE.RUL_SYSTEM_VARIABLE       ;
		TRUNCATE TABLE ZOERULE.RUL_RULE ;  
		TRUNCATE TABLE ZOERULE.RUL_MODEL_PROPERTY_DS_CFG ;
		TRUNCATE TABLE ZOERULE.RUL_RULE_CONTENT ;
		TRUNCATE TABLE ZOERULE.RUL_RULE_LABEL ;
		TRUNCATE TABLE ZOERULE.RUL_RULE_LABEL_MAP ;
		TRUNCATE TABLE ZOERULE.RUL_SYSTEM_VARIABLE ;
		INSERT INTO    ZOERULE.RUL_RULE                    SELECT * FROM ZOERULE.RUL_RULE@zoecdb41zoemdb                   ;
		INSERT INTO    ZOERULE.RUL_MODEL_PROPERTY_DS_CFG   SELECT * FROM ZOERULE.RUL_MODEL_PROPERTY_DS_CFG@zoecdb41zoemdb  ;
		INSERT INTO    ZOERULE.RUL_RULE_CONTENT            SELECT * FROM ZOERULE.RUL_RULE_CONTENT@zoecdb41zoemdb           ;
		INSERT INTO    ZOERULE.RUL_RULE_LABEL              SELECT * FROM ZOERULE.RUL_RULE_LABEL@zoecdb41zoemdb             ;
		INSERT INTO    ZOERULE.RUL_RULE_LABEL_MAP          SELECT * FROM ZOERULE.RUL_RULE_LABEL_MAP@zoecdb41zoemdb         ;
		INSERT INTO    ZOERULE.RUL_SYSTEM_VARIABLE         SELECT * FROM ZOERULE.RUL_SYSTEM_VARIABLE@zoecdb41zoemdb        ;

