-- Created in 2017.10.10 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		zoe_aud_deinstall.sql
--	Description:
-- 		卸载智业安全审计系统数据库部件
--  Relation:
--      
--	Notes:
--		使用zoesecurity用户连接创建
--	修改 - （年-月-日） - 描述
--

--根据需要设置创建审计对象当前用户
--ALTER SESSION SET CURRENT_SCHEMA=ZOESECURITY;

--禁用并删除触发器
--触发器："ZOETRG_AUD_DDL_BEFORE" 
ALTER TRIGGER ZOETRG_AUD_DDL_BEFORE DISABLE;
DROP TRIGGER ZOETRG_AUD_DDL_BEFORE;

--删除函数
DROP FUNCTION ZOEFUN_AUD_FIREWALL;
DROP FUNCTION ZOEFUN_AUD_GET_SESSION_CONTEXT;
DROP FUNCTION ZOEFUN_AUD_GET_SQL;
DROP FUNCTION ZOEFUN_AUD_INS_AUDIT_LOG;
DROP FUNCTION ZOEFUN_AUD_UPD_AUDIT_LOG;

--删除上下文关联包
DROP PACKAGE BODY ZOEPKG_AUDIT_SET_CONTEXT;
DROP PACKAGE ZOEPKG_AUDIT_SET_CONTEXT;

--删除上下文
DROP CONTEXT ZOE_AUDIT_CONTEXT;

--删除类型
DROP TYPE ZOETYP_AUD_SESSION_CONTEXT;
DROP TYPE ZOETYP_AUDIT_LOG;
DROP TYPE ZOETYP_AUD_FIREWALL;

--删除表
DROP TABLE ZOESECURITY.AUDIT_LOG CASCADE CONSTRAINT;

