CREATE OR REPLACE PACKAGE BODY ZOESECURITY.ZOEPKG_AUD_SET_CONTEXT AS
  PROCEDURE SET_AUD_CONTEXT(iv_name IN VARCHAR2,iv_value IN VARCHAR2) AS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('ZOE_AUD_CONTEXT',iv_name,UPPER(iv_value));
  EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ZOESECURITY.ZOEPKG_AUD_SET_CONTEXT:'||SQLERRM);
    NULL;
  END;
END ZOEPKG_AUD_SET_CONTEXT;
/

