CREATE OR REPLACE PACKAGE BODY ZOEPKG_AUDIT_SET_CONTEXT AS
  PROCEDURE SET_AUDIT_CONTEXT(iv_name IN VARCHAR2,iv_value IN VARCHAR2) AS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('ZOE_AUDIT_CONTEXT ',iv_name,UPPER(iv_value));
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END ZOEPKG_AUDIT_SET_CONTEXT;
/

