-- Created in 2018.10.11 by polarbears
-- Copyright (c) 20xx, CHINA and/or affiliates.
-- All rights reserved.
--	Name:
-- 		alert_db_space.sql
--	Description:
-- 		基本说明
--  Relation:
--      对象关联
--	Notes:
--		基本注意事项
--	修改 - （年-月-日） - 描述
--

--检查指标
	--数据库总使用率：  大于95%提醒
	--表空间剩余空间：  小于日均增量*90，增加数据文件
	--日志日增量：      大于日志日均增量3倍，提醒是否存在异常业务
	--日志最小切换时间：  小于3分钟，增加日志大小