--------------------------------------------------------
--  文件已创建 - 星期日-八月-12-2018   
--------------------------------------------------------
REM INSERTING into ZOEDEVOPS.DVP_DB_OBJ_ATTRB
SET DEFINE OFF;
Insert into ZOEDEVOPS.DVP_DB_OBJ_ATTRB (OBJ_TYPE_ID#,ATTRB_CODE,ATTRB_NAME,ATTRB_VALUE,OBJ_FLAG,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) values (3,'1','SEQUENCE_NAME',null,'N',null,null,null,null);
Insert into ZOEDEVOPS.DVP_DB_OBJ_ATTRB (OBJ_TYPE_ID#,ATTRB_CODE,ATTRB_NAME,ATTRB_VALUE,OBJ_FLAG,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) values (3,'2','SEQUENCE_START_WITH',null,'N',null,null,null,null);
Insert into ZOEDEVOPS.DVP_DB_OBJ_ATTRB (OBJ_TYPE_ID#,ATTRB_CODE,ATTRB_NAME,ATTRB_VALUE,OBJ_FLAG,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) values (3,'3','SEQUENCE_INCREMENT_BY',null,'N',null,null,null,null);
Insert into ZOEDEVOPS.DVP_DB_OBJ_ATTRB (OBJ_TYPE_ID#,ATTRB_CODE,ATTRB_NAME,ATTRB_VALUE,OBJ_FLAG,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) values (3,'4','SEQUENCE_CACHE',null,'N',null,null,null,null);
Insert into ZOEDEVOPS.DVP_DB_OBJ_ATTRB (OBJ_TYPE_ID#,ATTRB_CODE,ATTRB_NAME,ATTRB_VALUE,OBJ_FLAG,CREATOR_CODE,CREATED_TIME,MODIFIER_CODE,MODIFIED_TIME) values (3,'5','SEQUENCE_ORDER',null,'N',null,null,null,null);
